name: OpenAI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Generate diff
      - name: Generate diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt
          echo "Diff file created with size:"
          wc -l diff.txt

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 4: Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      - name: Run OpenAI Review Script
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # map your secret here
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PR_NUMBER: ${{ github.event.pull_request.number }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            run: python ci_script.py


      - name: Post comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('review_comment.txt', 'utf8');
            if (comment.trim()) {
            await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
            });
            } else {
            console.log("No review comment generated, skipping PR comment.");
            }

