name: OpenAI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write   # ensure workflow can comment on PRs

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to generate diff

      # Step 2: Generate diff between main and PR branch
      - name: Generate git diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt
          echo "Diff file created with size:"
          wc -l diff.txt

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      # Step 5: Run ci_script.py
      - name: Run OpenAI review script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.github-dani }}     # use your secret name
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ci_script.py

