name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write  # needed to post comments

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout code (skip submodules)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      # Step 2: Generate diff
      - name: Generate diff
        run: |
          TARGET_BRANCH=${{ github.base_ref }}
          git fetch origin $TARGET_BRANCH
          git diff origin/$TARGET_BRANCH...HEAD > diff.txt || echo "No changes"
          echo "Diff file created with size:"
          wc -l diff.txt

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 4: Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub azure-identity

      # Step 5: Run OpenAI Review Script
      - name: Run OpenAI Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ci_script.py
