name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write   # ✅ Needed for Azure OIDC login

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (no submodules to avoid errors)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      # Step 2: Generate git diff
      - name: Generate diff
        run: |
          TARGET_BRANCH=${{ github.base_ref }}
          git fetch origin $TARGET_BRANCH
          git diff origin/$TARGET_BRANCH...HEAD > diff.txt || echo "No changes"
          echo "Diff file created with size:"
          wc -l diff.txt

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 4: Install dependencies
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install openai PyGithub azure-identity

      # Step 5: Azure login (so DefaultAzureCredential works)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 6: Run PR review script
      - name: Run OpenAI Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ci_script.py


