name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write  # ✅ allow posting PR comments

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git branches
        run: |
          git branch -a
          git remote -v
          git log --oneline -5


      # Step 2: Generate diff
      - name: Generate diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt
          echo "Diff file created with size:"
          wc -l diff.txt

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 4: Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install openai azure-identity PyGithub

      # Step 5: Run Python review script
      - name: Run OpenAI Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ci_script.py
